gd_review/gd_review/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('levels/', include('levels.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

gd_review/levels/urls.py
from django.urls import path

from . import views


app_name = 'levels'


urlpatterns = [
    path('', views.LevelView.as_view(), name='level_list'),
    path('<int:level_id>/', views.LevelDetailsView.as_view(), name='level_detail'),
]

gd_review/pages/urls.py
from django.urls import path

from . import views


app_name = 'pages'


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

gd_review/users/urls.py
from django.urls import path

from . import views


app_name = 'users'


urlpatterns = [
    path('', views.UsersView.as_view(), name='user_list'),
    path('<str:username>/', views.ProfileView.as_view(), name='profile'),
]

gd_review/levels/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Avg
from django.utils import timezone


User = get_user_model()

DIFFICULTY_VALUES = {
    'AUTO': 1,
    'EASY': 2,
    'NORMAL': 3,
    'HARD': 4,
    'HARDER': 5,
    'INSANE': 6,
    'EASY DEMON': 7,
    'MEDIUM DEMON': 8,
    'HARD DEMON': 9,
    'INSANE DEMON': 10,
    'EXTREME DEMON': 11,
}


class Level(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField()
    difficulty = models.IntegerField(
        choices=[(val, name) for name, val in DIFFICULTY_VALUES.items()]
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(
        blank=True,
        default=timezone.now,
        verbose_name='Дата и время публикации',
        help_text=('Если установить дату и время '
                   'в будущем — можно делать отложенные публикации.'),
    )
    video_url = models.URLField(null=True)

    def average_difficulty(self):
        reviews = self.review_set.all()
        avg_difficulty = reviews.aggregate(Avg('difficulty'))
        return avg_difficulty['difficulty__avg'] if avg_difficulty['difficulty__avg'] else 0

    def __str__(self):
        return self.title[:50]


class Review(models.Model):
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    difficulty = models.IntegerField(choices=[(val, name) for name, val in DIFFICULTY_VALUES.items()])
    text = models.TextField(max_length=1024)
    pub_date = models.DateTimeField(
        blank=True,
        default=timezone.now,
        verbose_name='Дата и время публикации',
        help_text=('Если установить дату и время '
                   'в будущем — можно делать отложенные публикации.'),
    )

    def __str__(self):
        return self.text[:50]

gd_review/pages/models.py
from django.db import models

# Create your models here.

gd_review/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

ROLES = [
        ('Пользователь', 'user'),
        ('Модератор', 'moder'),
        ('Админ', 'admin'),
]


class MyUser(AbstractUser):
    bio = models.CharField(_('bio'), max_length=256, blank=True)
    role = models.CharField(
        _('role'),
        max_length=28,
        choices=ROLES,
        default='Пользователь'
    )

gd_review/levels/forms.py
from django import forms

from .models import Review


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('text', 'difficulty')

gd_review/levels/views.py
from django.db.models import Q
from django.views.generic import ListView, DetailView

from .consts import COUNT_POSTS_ON_PAGE, PK_URL_KWARG_FOR_LEVEL
from .forms import ReviewForm
from .models import Level, Review


class LevelView(ListView):
    model = Level
    template_name = 'levels/level_list.html'
    paginate_by = COUNT_POSTS_ON_PAGE

    def get_queryset(self):
        query = self.request.GET.get('search')
        if query:
            object_list = Level.objects.filter(
                Q(title__icontains=query) | Q(description__icontains=query)
            )
            return object_list
        queryset = self.model.objects.prefetch_related(
            'author',
        ).order_by(
            '-pub_date',
        )
        return queryset


class LevelDetailsView(DetailView):
    model = Level
    template_name = 'levels/level_detail.html'
    pk_url_kwarg = PK_URL_KWARG_FOR_LEVEL

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            id=self.kwargs[PK_URL_KWARG_FOR_LEVEL],
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ReviewForm()
        context['reviews'] = Review.objects.select_related('author').filter(
            level_id=self.kwargs[PK_URL_KWARG_FOR_LEVEL],
        )
        return context

gd_review/pages/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'pages/index.html')


def about(request):
    return render(request, 'pages/about.html')

gd_review/users/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView

from levels.consts import COUNT_POSTS_ON_PAGE
from levels.models import Review
from .models import MyUser


class UsersView(ListView):
    model = MyUser
    template_name = 'users/users.html'
    paginate_by = COUNT_POSTS_ON_PAGE

    def get_queryset(self):
        query = self.request.GET.get('search')
        if query:
            object_list = MyUser.objects.filter(
                Q(username__icontains=query)
            )
            return object_list
        queryset = self.model.objects.order_by(
            'username',
        )
        return queryset


class ProfileView(DetailView):
    model = MyUser
    template_name = 'users/profile.html'
    pk_url_kwarg = 'username'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, username=self.kwargs.get(self.pk_url_kwarg))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews'] = Review.objects.select_related('author')
        return context

gd_review/levels/templates/includes/level_card.html
{% load embed_video_tags %}
<style>
  .card {
    margin: 10px;
    border-radius: 5px;
  }
  .card-img-top {
    height: 200px;
    object-fit: cover;
  }
</style>
<div class="col-md-4">
  <div class="card">
    {% video level.video_url as video %}
      {% if video in None %}
        <img src="https://via.placeholder.com/300x200" class="card-img-top" alt="Level Image">
      {% else %}
        <img src="{{ video.thumbnail }}" class="card-img-top" alt="Video Preview">
      {% endif %}
    {% endvideo %}
  <div class="card-body">
    <h5 class="card-title">{{ level.title }}</h5>
    <p class="card-text">{{ level.description|truncatechars:30 }}</p>
    <a href="{% url 'levels:level_detail' level.id %}" class="btn btn-primary">Подробнее</a>
  </div>
  </div>
</div>

gd_review/levels/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

gd_review/levels/templates/includes/reviews.html
{#{% if user.is_authenticated %}#}
{#  {% load django_bootstrap5 %}#}
{#  <h5 class="mb-4">Оставить комментарий</h5>#}
{#  <form method="post" action="{% url 'blog:add_comment' post.id %}">#}
{#    {% csrf_token %}#}
{#    {% bootstrap_form form %}#}
{#    {% bootstrap_button button_type="submit" content="Отправить" %}#}
{#  </form>#}
{#{% endif %}#}
<br>
{% for review in reviews %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'users:profile' review.author.username %}" name="review_{{ review.id }}">
          @{{ review.author.username }}
        </a>
      </h5>
      <small class="text-muted">{{ review.pub_date }}</small>
      <br>
      {{ review.text|linebreaksbr }}
    </div>
{#    {% if user == review.author %}#}
{#      <a class="btn btn-sm text-muted" href="{% url 'blog:edit_comment' post.id review.id %}" role="button">#}
{#        Отредактировать комментарий#}
{#      </a>#}
{#      <a class="btn btn-sm text-muted" href="{% url 'blog:delete_comment' post.id review.id %}" role="button">#}
{#        Удалить комментарий#}
{#      </a>#}
{#    {% endif %}#}
  </div>
{% endfor %}

gd_review/levels/templates/levels/level_detail.html
{% extends "base.html" %}
{% load embed_video_tags %}
{% block title %}
  {{ level.title }}
{% endblock %}
{% block content %}
  <div class="container">
    <h1>{{ level.title }}</h1>
    <p>{{ level.description }}</p>
    {% video level.video_url %}
    <p>Сложность: {{ level.difficulty }}</p>
    <p>Дата публикации: {{ level.pub_date }}</p>
    <p>Средняя сложность: {{ level.average_difficulty }}</p>
    <hr>
    {% include "includes/reviews.html" %}
  </div>
{% endblock %}

gd_review/levels/templates/levels/level_list.html
{% extends "base.html" %}

{% block title %}
  Список уровней
{% endblock %}

{% block content %}
<div class="container-fluid p-5">
  <div class="row" style="margin-top: -50px">
  {% for level in page_obj %}
        {% include "includes/level_card.html" %}
  {% endfor %}
      </div>
    </div>
  {% include "includes/paginator.html" %}
{% endblock %}

gd_review/pages/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <title>Главная страница</title>
  <style>
    main {
        position: fixed;
        height: 100%;
        width: 100%;
        overflow-y: auto
    }
  </style>
</head>
<body>

  <main class="d-flex">

    {% include "includes/sidebar.html" %}

    <div class="container-fluid" style="margin-left: 300px; margin-top: 50px">
      {% block content %}{% endblock %}
    </div>

  </main>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybBud7TlRbs/ic4AwGcFZOxg5DpPt8EgeUIgIwzjWfXQKWA3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>


</body>
</html>

gd_review/pages/templates/includes/sidebar.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary" style="width: 280px; position: fixed; height: 100%; overflow-y: auto; box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1);">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
    <svg class="bi pe-none me-2" width="50" height="40">
      <image xlink:href="{% static 'logo/logo.svg' %}" width="50" height="40" />
    </svg>
    <span class="fs-4">GD Review</span>
  </a>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <a href="{% url 'pages:index' %}" class="nav-link {% if view_name == 'pages:index' %} active {% else %} link-body-emphasis {% endif %}" aria-current="page">
        <svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="currentColor" class="bi bi-house" viewBox="0 -2 20 20">
          <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"/>
        </svg>
        Home
      </a>
    </li>
    <li>
      <a href="{% url 'levels:level_list' %}" class="nav-link {% if view_name == 'levels:level_list' %} active {% else %} link-body-emphasis {% endif %}" aria-current="page">
        <svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="currentColor" class="bi bi-list-stars" viewBox="0 -2.5 20 20">
          <path fill-rule="evenodd" d="M5 11.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5"/>
          <path d="M2.242 2.194a.27.27 0 0 1 .516 0l.162.53c.035.115.14.194.258.194h.551c.259 0 .37.333.164.493l-.468.363a.28.28 0 0 0-.094.3l.173.569c.078.256-.213.462-.423.3l-.417-.324a.27.27 0 0 0-.328 0l-.417.323c-.21.163-.5-.043-.423-.299l.173-.57a.28.28 0 0 0-.094-.299l-.468-.363c-.206-.16-.095-.493.164-.493h.55a.27.27 0 0 0 .259-.194zm0 4a.27.27 0 0 1 .516 0l.162.53c.035.115.14.194.258.194h.551c.259 0 .37.333.164.493l-.468.363a.28.28 0 0 0-.094.3l.173.569c.078.255-.213.462-.423.3l-.417-.324a.27.27 0 0 0-.328 0l-.417.323c-.21.163-.5-.043-.423-.299l.173-.57a.28.28 0 0 0-.094-.299l-.468-.363c-.206-.16-.095-.493.164-.493h.55a.27.27 0 0 0 .259-.194zm0 4a.27.27 0 0 1 .516 0l.162.53c.035.115.14.194.258.194h.551c.259 0 .37.333.164.493l-.468.363a.28.28 0 0 0-.094.3l.173.569c.078.255-.213.462-.423.3l-.417-.324a.27.27 0 0 0-.328 0l-.417.323c-.21.163-.5-.043-.423-.299l.173-.57a.28.28 0 0 0-.094-.299l-.468-.363c-.206-.16-.095-.493.164-.493h.55a.27.27 0 0 0 .259-.194z"/>
        </svg>
        Levels
      </a>
    </li>

    <li>
    <a href="{% url 'users:user_list' %}" class="nav-link {% if view_name == 'users:user_list' %} active {% else %} link-body-emphasis {% endif %}" aria-current="page">
      <svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="currentColor" class="bi bi-people" viewBox="0 -1.5 20 20">
        <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1zm-7.978-1L7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002-.014.002zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4m3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0M6.936 9.28a6 6 0 0 0-1.23-.247A7 7 0 0 0 5 9c-4 0-5 3-5 4q0 1 1 1h4.216A2.24 2.24 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816M4.92 10A5.5 5.5 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275ZM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0m3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4"/>
      </svg>
      Users
    </a>
    </li>
    <li>
      <a href="{% url 'pages:about' %}" class="nav-link {% if view_name == 'pages:about' %} active {% else %} link-body-emphasis {% endif %}" aria-current="page">
        <svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="currentColor" class="bi bi-book" viewBox="0 -2 20 20">
          <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783"/>
        </svg>
        About
      </a>
    </li>
    {% if view_name == 'levels:level_list' or view_name == 'users:user_list'%}
      <form action="{% if view_name == 'users:user_list' %} {% url 'users:user_list' %} {% else %} {% url 'levels:level_list' %} {% endif %}" method="get" class="d-flex mb-3" style="margin-top: 10px;">
        <input name='search' class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary" type="submit">
          <img src="{% static 'svg/search.svg' %}" width="20" height="25">
        </button>
      </form>
    {% endif %}
  </ul>
  <hr>
  <div>
    <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none" aria-expanded="false">
      <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
      <strong>mdo</strong>
    </a>
  </div>
</div>
{% endwith %}

gd_review/pages/templates/pages/about.html
{% extends "base.html" %}

{% block title %}
  О сайте
{% endblock %}

{% block content %}
<h1>О сайте</h1>
{% endblock %}

gd_review/pages/templates/pages/index.html
{% extends "base.html" %}

{% block title %}
  Главная страница
{% endblock %}

{% block content %}
<h1>uifhguisdfg</h1>
{% endblock %}

gd_review/users/templates/includes/user_card.html
<style>
  .card {
    margin: 10px;
    border-radius: 5px;
  }
</style>
<div class="col-md-4">
  <div class="card">
    <div class="card-body">
      <div class="d-flex align-items-center">
          <img src="https://github.com/mdo.png" alt="" width="50" height="50" class="rounded-circle me-3">
          <h5 class="card-title me-3">{{ user.username|truncatechars:30 }}</h5>
      </div>
      <p class="card-text" style="margin-top: 10px">{{ user.bio|truncatechars:30 }}фывфыв</p>
      <a href="{% url 'users:profile' user.username %}" class="btn btn-primary">Подробнее</a>
    </div>
  </div>
</div>

gd_review/users/templates/users/profile.html
{% extends "base.html" %}

{% block title %}
  Профиль - {{ user.username }}
{% endblock %}

{% block content %}
  <div class="container">
    <img src="https://github.com/mdo.png" alt="" width="100" height="100" class="rounded-circle me-3">
    <h1>{{ user.username }}</h1>
    <p>{{ user.bio }}fdsfsdf</p>
    <hr>
    {% include "includes/reviews.html" %}
  </div>
{% endblock %}

gd_review/users/templates/users/users.html
{% extends "base.html" %}

{% block title %}
  Список пользователей
{% endblock %}

{% block content %}
  <div class="container-fluid p-5">
    <div class="row" style="margin-top: -50px">
      {% for user in page_obj %}
        {% include "includes/user_card.html" %}
      {% endfor %}
    </div>
  </div>
  {% include "includes/paginator.html" %}
{% endblock %}